zuihou:
  mysql:
    ip: ${MYSQL_IP:106.52.150.44}
    port: 3306
    username: root
    password: Aa123456

xxl.job:
  executor:
    ip: ${EXECUTOR_IP:127.0.0.1}
    port: ${EXECUTOR_PORT:8771}

spring:
  profiles:
    active: dev
